<?php

function grant_reporting_permission()
{
	return array(
		'administer grant reporting' => array(
			'title' => t( 'Administer Grant Reporting' ),
			'description' => t( 'Add grants, add activities' ),
		),
		'report grant activity' => array(
			'title' => t( 'Report Grant Activity' ),
			'description' => t( 'Report activity that relates to grants' ),
		),	
		'access grant reports' => array(
			'title' => t( 'Access Grant Reports' ),
			'description' => t( 'View reports of grants' ),
		)
	);
}

function grant_reporting_menu()
{
	$items['admin/config/grant'] = array(
		'title' => 'Grant Reporting',
		'position' => 'right',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'grant_reporting_config_form' ),
		'access arguments' => array( 'administer grant reporting' ),
	);

	$items['admin/config/grant/reports'] = array(
		'title' => 'Grant Report Configuration',
		'description' => 'Configure the grants and activities under those grants',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'grant_reporting_config_form' ),
		'access arguments' => array( 'administer grant reporting' ),
	);

	$items['grant-report-form'] = array(
		'title' => 'Grant Report Form',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'grant_reporting_report_form' ),
		'access arguments' => array( 'report grant activity' ),
	);

	$items['grant-report'] = array(
		'title' => 'Generate Grant Report',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'grant_reporting_generate_form' ),
		'access arguments' => array( 'access grant reports' ),
	);

	$items['grant-report/%/%/%'] = array(
		'title' => 'Grant Report',
		'page callback' => 'grant_reporting_report',
		'page arguments' => array( 1, 2, 3 ),
		'access arguments' => array( 'access grant reports' ),
	);

	$items['grant-report-detail'] = array(
		'title' => 'Generate Detailed Grant Report',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'grant_reporting_generate_detail_form' ),
		'access arguments' => array( 'access grant reports' ),
	);

	$items['grant-report-detail/%/%/%'] = array(
		'title' => 'Detailed Grant Report',
		'page callback' => 'grant_reporting_detail',
		'page arguments' => array( 1, 2, 3 ),
		'access arguments' => array( 'access grant reports' ),
	);

	return $items;
}

function grant_reporting_config_form()
{
	$form = array();

	$form['description'] = array(
		'#markup' => '<p>This form allows you to add grants and activities</p>',
	);

	# Grant fieldset
	$form['grants'] = array(
		'#type' => 'fieldset',
		'#title' => t( 'Grants' ),
	);

	$form['grants']['old_grants'] = array(
		'#markup' => "<ul><li>"
			. implode( '</li><li>', create_grant_list() )
			. "</li></ul>",
	);

	$form['grants']['new_grant'] = array(
		'#type' => 'textfield',
		'#title' => 'Add Grant',
	);
	 
	# Activity fieldset
	$form['activities'] = array(
		'#type' => 'fieldset',
		'#title' => t( 'Activities' ),
	);

	$form['activities']['old_activities'] = array(
		'#markup' => "<ul><li>"
			. implode( '</li><li>', create_activity_list() )
			. "</li></ul>",
	);

	$form['activities']['new_activity'] = array(
		'#type' => 'textfield',
		'#title' => 'Add Activity',
	);

	# Submit
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Submit',
	);

	return $form;
}

function grant_reporting_config_form_submit( $form, &$form_state )
{
	# Add grant
	if ( !empty( $form_state['values']['new_grant'] ) )
	{
		db_insert( 'grants' )
			->fields( array( 'grant_name' => $form_state['values']['new_grant'] ) )
			->execute();

		drupal_set_message( "New grant added!" );
	}

	# Add activity
	if ( !empty( $form_state['values']['new_activity'] ) )
	{
		db_insert( 'grant_activities' )
			->fields( array( 'activity_name' => $form_state['values']['new_activity'] ) )
			->execute();

		drupal_set_message( "New activity added!" );
	}
}

function grant_reporting_report_form()
{
	$form = array();

	$form['description'] = array(
		'#markup' => '<p>This form is for reporting activity that falls under a certain grant.</p>',
	);

	# Gather grant options
	$form['grant'] = array(
		'#type' => 'select',
		'#title' => 'Choose a grant to file this activity under',
		'#options' => create_grant_list(),
	);

	# Gather activity options
	$form['activity'] = array(
		'#type' => 'select',
		'#title' => 'Choose an activity to record',
		'#options' => create_activity_list(),
	);

	# Allow user to enter time that the activity occurred
	$form['date'] = array(
		'#type' => 'date',
		'#title' => 'Select date that this activity occurred',
	);

	# User enters name of person contacted
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => 'Enter full name of person contacted',
		'#maxlength' => 255,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Submit'
	);

	return $form;
}

function grant_reporting_report_form_submit( $form, &$form_state )
{
	# Concatenate date values into an int
	$date = intval(
		$form_state['values']['date']['year']
		. str_pad( $form_state['values']['date']['month'], 2, '0', STR_PAD_LEFT )
		. str_pad( $form_state['values']['date']['day'], 2, '0', STR_PAD_LEFT ) );

	global $user;

	db_insert( 'grant_report' )
		->fields(
			array(
				'gid' => intval( $form_state['values']['grant'] ),
				'gaid' => intval( $form_state['values']['activity'] ),
				'uid' => $user->uid,
				'date' => $date,
				'name' => $form_state['values']['name'],
			)
		)->execute();
				
	drupal_set_message( "Report submitted!" );
}

function grant_reporting_generate_form()
{
	$form = array();

	$form['description'] = array(
		'#markup' => '<p>Enter a grant and a date to generate a report for that month</p>',
	);

	$form['grant'] = array(
		'#type' => 'select',
		'#title' => t( 'Select a grant:' ),
		'#options' => create_grant_list(),
		'#required' => TRUE,
	);

	$form['date'] = array(
		'#type' => 'date_select',
		'#title' => t( "Select a date:" ),
		'#date_year_range' => '2012:+1',
		'#date_format' => 'Y-M',
		'#default_value' => date( "Y-M" ),
		'#required' => TRUE,
	);

	$form['user'] = array(
		'#type' => 'select',
		'#title' => t( "(Optional) Select a user:" ),
		'#options' => create_user_list(),
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Generate Report!',
	);

	return $form;
}

function grant_reporting_generate_form_submit( $form, &$form_state )
{
	$gid = $form_state['values']['grant'];
	$uid = $form_state['values']['user'];
	$year = substr( $form_state['values']['date'], 0, 4 );
	$month = substr( $form_state['values']['date'], -2 );

	$form_state['redirect'] = "grant-report/$gid/$year/$month";

	if ( !empty( $uid ) )
		$form_state['redirect'] .= "/$uid";
}

function grant_reporting_report( $gid, $year, $month, $uid = 0 )
{
	# Beginning and end of month (technically the number of days)
	$begin = '00';
	$end = '99';

	# Find out the title of the grant we're dealing with
	$grant_name = get_grant_name( $gid );
	
	# Stop date will always be the same
	$stop = $year . str_pad( $month, 2, '0', STR_PAD_LEFT ) . $end;
	$end_string = date( "F", mktime( 0, 0, 0, $month, 1 ) ) . ", $year";

	# Set an appropriate title
	if ( $uid != 0 )
		drupal_set_title( get_user_name( $uid ) . "'s $grant_name report for $end_string" );
	else
		drupal_set_title( "$grant_name report for $end_string" );

	####################
	# Print month data #
	####################

	# Start date
	$start = $year . str_pad( $month, 2, '0', STR_PAD_LEFT ) . $begin;

	# Print header and table
	$output = "<h3>Month's Report ($end_string):</h3>";
	$output .= activity_count_table( $gid, $uid, $start, $stop );

	######################
	# Print quarter data #
	######################

	# Start info
	$start_month = ( $month + 9 ) % 12 + 1;
	$start_year = $year - ( $month < 3 ? 1 : 0 );
	$start = $start_year . str_pad( $start_month, 2, '0', STR_PAD_LEFT ) . $begin;

	# Human-readable month name + year
	$start_string = get_date_string( $start_year, $start_month );

	# Print header and table
	$output .= "<h3>Quarter's Report ($start_string - $end_string):</h3>";
	$output .= activity_count_table( $gid, $uid, $start, $stop );

	###################
	# Print year data #
	###################

	# Start info
	$start_year = $year - 1;
	$start_month = $month % 12 + 1;
	$start = $start_year . str_pad( $start_month, 2, '0', STR_PAD_LEFT ) . $begin;
	
	# Human-readable month name + year
	$start_string = get_date_string( $start_year, $start_month );

	# Print header and table
	$output .= "<h3>Year's Report ($start_string - $end_string):</h3>";
	$output .= activity_count_table( $gid, $uid, $start, $stop );

	##############
	# Print Link #
	##############
	$output .= "<p>Go back to " . l( 'Report Generator', '/grant-report' ) . ".</p>";

	return $output;
}

function grant_reporting_generate_detail_form()
{
	$form = array();

	$form['description'] = array(
		'#markup' => '<p>Enter a grant and a start and end date to generate a detailed report for that month</p>',
	);

	$form['grant'] = array(
		'#type' => 'select',
		'#title' => t( 'Select a grant:' ),
		'#options' => create_grant_list(),
		'#required' => TRUE,
	);

	// Start date default is one year ago
	$form['begin'] = array(
		'#type' => 'date_select',
		'#title' => t( 'Select a start date:' ),
		'#date_year_range' => '2012:+0',
		'#date_format' => 'Y-M',
		'#default_value' => date( 'Y-M', time() - 31557600 ),
		'#required' => TRUE,
	);

	// End date default is now
	$form['end'] = array(
		'#type' => 'date_select',
		'#title' => t( 'Select an end date:' ),
		'#date_year_range' => '2012:+0',
		'#date_format' => 'Y-M',
		'#default_value' => date( 'Y-M' ),
		'#required' => TRUE,
	);

	$form['user'] = array(
		'#type' => 'select',
		'#title' => t( "(Optional) Select a user:" ),
		'#options' => create_user_list(),
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Generate Detailed Report!',
	);

	return $form;
}

function grant_reporting_generate_detail_form_submit( $form, &$form_state )
{
	$gid = $form_state['values']['grant'];
	$begin = $form_state['values']['begin'];
	$end = $form_state['values']['end'];
	$uid = $form_state['values']['user'];

	$form_state['redirect'] = "grant-report-detail/$gid/$begin/$end";

	if ( !empty( $uid ) )
		$form_state['redirect'] .= "/$uid";
}

function grant_reporting_detail( $gid, $begin, $end, $uid = 0 )
{
	$output = '';

	$grant_name = get_grant_name( $gid );

	// Format dates
	$begin = str_replace( '-', '', $begin );
	$end = str_replace( '-', '', $end );
	$begin_date = get_date_string( parse_year( $begin ), parse_month( $begin ) );
	$end_date = get_date_string( parse_year( $end ), parse_month( $end ) );

	$output .= '<p>';
	if ( $uid )
		$output .= get_user_name( $uid ) . "'s ";
	
	$output .= "Activity on the $grant_name grant from $begin_date to $end_date.</p>";

	$output .= activity_detail_table( $gid, $uid, $begin, $end );
	
	return $output;
}

function parse_year( $date ) { return intval( substr( $date, 0, 4 ) ); }
function parse_month( $date ) { return intval( substr( $date, 4, 2 ) ); }
function parse_day( $date ) { return intval( substr( $date, 6, 2 ) ); }

function get_date_string( $year, $month, $day = 0 )
{
	if ( $day )
		$date_string = date( "F j, Y", mktime( 0, 0, 0, $month, $day, $year ) );
	else
		$date_string = date( "F, Y", mktime( 0, 0, 0, $month, 1, $year ) );

	return $date_string;
}

function activity_detail_table( $gid, $uid, $begin, $end )
{
	$activity_query = db_select( 'grant_report', 'gr' );
	$activity_query->join( 'grant_activities', 'ga', 'gr.gaid = ga.gaid' );
	$activity_query->join( 'users', 'u', 'gr.uid = u.uid' );

	$activity_query->fields( 'gr', array( 'name', 'date' ) )
		->fields( 'ga', array( 'activity_name' ) )
		->addField( 'u', 'name', 'username' );
	
	$activity_query->condition( 'gid', $gid )
		->condition( 'date', $begin . '00', '>' )
		->condition( 'date', $end . '99', '<' );

	if ( $uid )
		$activity_query->condition( 'uid', $uid );

	$activity_query->orderBy( 'date', 'DESC' );
	$activities = $activity_query->execute();

	$rows = array();
	while ( $activity = $activities->fetchAssoc() )
	{
		$year = parse_year( $activity['date'] );
		$month = parse_month( $activity['date'] );
		$day = parse_day( $activity['date'] );
		$rows[] = array(
			$activity['name'],
			$activity['username'],
			$activity['activity_name'],
			get_date_string( $year, $month, $day ),
		);
	}

	return theme(
		'table',
		array(
			'header' => array( 'Person helped', 'Advocate', 'Activity', 'Date' ),
			'rows' => $rows,
		)
	);
}

function activity_count_table( $gid, $uid, $start, $stop )
{
	$activities = create_activity_list();
	
	$rows = array();
	
	foreach ( $activities as $gaid => $activity )
		$rows[] = array( $activity, count_activities( $gid, $gaid, $uid, $start, $stop ) );
	
	return theme(
		'table',
		array(
			'header' => array( 'Activity', 'Count' ),
			'rows' => $rows,
		)
	);
}

function count_activities( $gid, $gaid, $uid, $start, $end )
{
	$activity_count = db_select( 'grant_report' )
		->condition( 'gid', $gid )
		->condition( 'gaid', $gaid )
		->condition( 'date', $start, '>' )
		->condition( 'date', $end, '<' );

	if ( !empty( $uid ) )
		$activity_count = $activity_count->condition( 'uid', $uid );

	return $activity_count->countQuery()->execute()->fetchField();
}

function create_grant_list()
{
	$grants_result = db_select( 'grants' )
		->fields( 'grants', array( 'gid', 'grant_name' ) )
		->execute();

	$grants = array();
	while ( $grant = $grants_result->fetchAssoc() )
		$grants[$grant['gid']] = $grant['grant_name'];

	return $grants;
}

function create_activity_list()
{
	$activities_result = db_select( 'grant_activities' )
		->fields( 'grant_activities', array( 'gaid', 'activity_name' ) )
		->execute();

	$activities = array();
	while ( $activity = $activities_result->fetchAssoc() )
		$activities[$activity['gaid']] = $activity['activity_name'];

	return $activities;
}

function create_user_list()
{
	$user_result = db_select( 'grant_report' )
		->fields( 'grant_report', array( 'uid' ) )
		->distinct()
		->execute();

	$users = array( '' );
	while ( $uid = $user_result->fetchField() )
		$users[$uid] = get_user_name( $uid ); 

	return $users;
}

function get_user_name( $uid )
{
	$name = db_select( 'users' )
		->fields( 'users', array( 'name' ) )
		->condition( 'uid', $uid )
		->execute()
		->fetchField();

	return $name;
}

function get_grant_name( $gid )
{
	$name = db_select( 'grants' )
		->fields( 'grants', array( 'grant_name' ) )
		->condition( 'gid', $gid )
		->execute()
		->fetchField();
	
	return $name;
}
